Courtesy of:
- https://gist.github.com/bsweger/e5817488d161f37dcbd2
- https://jeffdelaney.me/blog/useful-snippets-in-pandas/
- and my own experience

Datasets created by AWS.

In [1]:
import pandas as pd

## Notebook introduction
We have created this notebook to reduce the startup time for new data scientists with
little or no previous exposure to Python and Pandas. We will use two simple csv files to
drive all the examples. The first contains a set of users, and the second has a set
of zip codes. Each snippet will provide a working example of a commonly used operation on a Pandas dataframe.

In [2]:
!head users.csv

USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV
3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia
13,39,FEMALE,92335,35008,51,25,OLDISH-BMW-430i
15,38,FEMALE,77449,59198,56,28,NEWISH-Buick-Regal
20,40,MALE,77494,86488,73,36,OLDISH-Ford-Fusion
24,42,FEMALE,90805,32565,53,26,OLDISH-Ford-Explorer
29,37,MALE,10458,22072,50,25,NEWISH-BMW-430i
32,44,FEMALE,85364,31515,11,5,OLDISH-Nissan-Altima
36,36,MALE,92154,42970,33,16,OLDISH-Ford-Escape
39,40,MALE,60618,41355,72,36,NEWISH-Ford-Fusion

In [3]:
!head zip_codes.csv

ZIP_CODE,CITY,INCOME
79936,El Paso TX,42857
90011,Los Angeles CA,23851
60629,Chicago IL,40279
90650,Norwalk CA,46012
90201,Bell Gardens CA,30029
77084,Houston TX,53075
92335,Fontana CA,35008
78521,Brownsville TX,23426
77449,Katy TX,59198

### Create dataframe from csv

In [4]:
df        = pd.read_csv('users.csv')
df_skinny = pd.read_csv('users.csv', usecols=['LOCATION', 'SALARY'])
df_zip    = pd.read_csv('zip_codes.csv')

### Show shape of dataframe (num rows, num cols)

In [5]:
df.shape

(23364, 8)

In [6]:
df_zip.shape

(100, 3)

In [7]:
df_skinny.shape

(23364, 2)

In [8]:
print('Num rows in user dataframe: {}'.format(df.shape[0]))

Num rows in user dataframe: 23364

### Show column types

In [9]:
df.dtypes

USER_ID         int64
AGE             int64
GENDER         object
LOCATION        int64
SALARY          int64
FAV_CLUSTER     int64
FAV_MODEL       int64
FAV            object
dtype: object

### Show column types and dataframe size and memory consumption

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23364 entries, 0 to 23363
Data columns (total 8 columns):
USER_ID        23364 non-null int64
AGE            23364 non-null int64
GENDER         23364 non-null object
LOCATION       23364 non-null int64
SALARY         23364 non-null int64
FAV_CLUSTER    23364 non-null int64
FAV_MODEL      23364 non-null int64
FAV            23364 non-null object
dtypes: int64(6), object(2)
memory usage: 1.4+ MB

### Get basic statistics (std, min, max, ...) on numeric columns

In [11]:
df.describe()

,USER_ID,AGE,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL
count,23364.000000,23364.000000,23364.000000,23364.000000,23364.000000,23364.000000
mean,15034.053030,39.527050,62234.150959,42100.189950,49.483564,24.490584
std,7363.301444,3.981971,34214.804242,16215.603001,16.111937,8.058349
min,3.000000,25.000000,926.000000,16664.000000,0.000000,0.000000
25%,9112.750000,37.000000,22193.000000,31013.000000,39.000000,19.000000
50%,15038.500000,40.000000,77573.000000,39225.000000,49.000000,24.000000
75%,20973.250000,42.000000,91710.000000,48744.000000,60.000000,30.000000
max,29992.000000,57.000000,95823.000000,96118.000000,99.000000,49.000000

### Show some rows from top or bottom of dataframe

In [12]:
df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia
1,13,39,FEMALE,92335,35008,51,25,OLDISH-BMW-430i
2,15,38,FEMALE,77449,59198,56,28,NEWISH-Buick-Regal
3,20,40,MALE,77494,86488,73,36,OLDISH-Ford-Fusion
4,24,42,FEMALE,90805,32565,53,26,OLDISH-Ford-Explorer

In [13]:
df.head(2)

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia
1,13,39,FEMALE,92335,35008,51,25,OLDISH-BMW-430i

In [14]:
df.tail(3)

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV
23361,29988,44,MALE,90805,32565,83,41,OLDISH-Volkswagen-Tiguan
23362,29989,34,FEMALE,60629,40279,69,34,OLDISH-Cadillac-XT5
23363,29992,35,MALE,37211,37141,67,33,OLDISH-Chevrolet-Camaro

In [15]:
df_zip.head(3)

   ZIP_CODE            CITY  INCOME
0     79936      El Paso TX   42857
1     90011  Los Angeles CA   23851
2     60629      Chicago IL   40279

### Show columns

In [16]:
df.columns

Index(['USER_ID', 'AGE', 'GENDER', 'LOCATION', 'SALARY', 'FAV_CLUSTER',
       'FAV_MODEL', 'FAV'],
      dtype='object')

In [17]:
df_zip.columns

Index(['ZIP_CODE', 'CITY', 'INCOME'], dtype='object')

### Show count of each unique value in a column

In [18]:
df['AGE'].value_counts()

40    2359
39    2283
38    2185
41    2132
37    1966
42    1929
36    1557
43    1553
44    1247
35    1231
34     937
45     929
46     661
33     614
32     387
47     383
48     242
31     218
49     158
30     142
29      68
50      55
51      44
28      33
52      15
27      10
26       7
54       6
53       5
25       4
56       2
57       1
55       1
Name: AGE, dtype: int64

### Create a new column based on an existing column
Here we use a simple function to make a new DECADE column from AGE.

In [19]:
def decade(age):
    return age // 10
df['DECADE'] = df['AGE'].apply(decade)
df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia,3
1,13,39,FEMALE,92335,35008,51,25,OLDISH-BMW-430i,3
2,15,38,FEMALE,77449,59198,56,28,NEWISH-Buick-Regal,3
3,20,40,MALE,77494,86488,73,36,OLDISH-Ford-Fusion,4
4,24,42,FEMALE,90805,32565,53,26,OLDISH-Ford-Explorer,4

### Show subset of rows by index
Here we show rows 5 and 6

In [20]:
df[5:7]

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
5,29,37,MALE,10458,22072,50,25,NEWISH-BMW-430i,3
6,32,44,FEMALE,85364,31515,11,5,OLDISH-Nissan-Altima,4

### Merge two datasets on a column

In [21]:
df_extended = pd.merge(df, df_zip, left_on='LOCATION', right_on='ZIP_CODE')
df_extended.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE,ZIP_CODE,CITY,INCOME
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia,3,60647,Chicago IL,35283
1,530,41,FEMALE,60647,35283,52,26,NEWISH-Ford-Explorer,4,60647,Chicago IL,35283
2,910,36,FEMALE,60647,35283,50,25,NEWISH-BMW-430i,3,60647,Chicago IL,35283
3,1238,40,FEMALE,60647,35283,23,11,OLDISH-GMC-Acadia,4,60647,Chicago IL,35283
4,1443,38,FEMALE,60647,35283,47,23,OLDISH-Chrysler-Pacifica,3,60647,Chicago IL,35283

In [22]:
df_extended.shape

(23364, 12)

### Drop a column

In [23]:
df_extended.drop(columns='LOCATION', inplace=True)
df_extended.head()

,USER_ID,AGE,GENDER,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE,ZIP_CODE,CITY,INCOME
0,3,35,FEMALE,35283,22,11,NEWISH-GMC-Acadia,3,60647,Chicago IL,35283
1,530,41,FEMALE,35283,52,26,NEWISH-Ford-Explorer,4,60647,Chicago IL,35283
2,910,36,FEMALE,35283,50,25,NEWISH-BMW-430i,3,60647,Chicago IL,35283
3,1238,40,FEMALE,35283,23,11,OLDISH-GMC-Acadia,4,60647,Chicago IL,35283
4,1443,38,FEMALE,35283,47,23,OLDISH-Chrysler-Pacifica,3,60647,Chicago IL,35283

### Rename a column

In [24]:
df_zip.rename(columns={'ZIP_CODE':'LOCATION'}, inplace=True)
df_zip.head()

   LOCATION             CITY  INCOME
0     79936       El Paso TX   42857
1     90011   Los Angeles CA   23851
2     60629       Chicago IL   40279
3     90650       Norwalk CA   46012
4     90201  Bell Gardens CA   30029

### Save a dataframe to a csv file
First, we use a header. Then we try it without saving a header. In both cases, we choose
to not save the indices as a column.

In [25]:
df_zip.to_csv('tmp_zip.csv', index=False, header=None)
!head tmp_zip.csv

79936,El Paso TX,42857
90011,Los Angeles CA,23851
60629,Chicago IL,40279
90650,Norwalk CA,46012
90201,Bell Gardens CA,30029
77084,Houston TX,53075
92335,Fontana CA,35008
78521,Brownsville TX,23426
77449,Katy TX,59198
78572,Mission TX,23799

In [26]:
df_zip.to_csv('tmp_zip.csv', index=False)
!head tmp_zip.csv

LOCATION,CITY,INCOME
79936,El Paso TX,42857
90011,Los Angeles CA,23851
60629,Chicago IL,40279
90650,Norwalk CA,46012
90201,Bell Gardens CA,30029
77084,Houston TX,53075
92335,Fontana CA,35008
78521,Brownsville TX,23426
77449,Katy TX,59198

### Create a new dataframe from a list

In [27]:
tmp = []
tmp.append(['toyota', 'camry', 2015])
tmp.append(['chevrolet', 'silverado', 2011])
tmp_df = pd.DataFrame(tmp, columns=['Make', 'Model', 'Year'])
tmp_df.head()

        Make      Model  Year
0     toyota      camry  2015
1  chevrolet  silverado  2011

### Select subset of rows based on single column criteria

In [28]:
tmp_df = df[df.USER_ID == 3]
tmp_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia,3

### Select subset of rows based on multiple column criteria

In [29]:
tmp_df = df[(df.AGE > 38) & (df.SALARY < 30000)]
tmp_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
11,50,41,FEMALE,10467,29044,79,39,OLDISH-Toyota-Prius,4
29,122,42,FEMALE,90044,22091,42,21,NEWISH-Nissan-Rogue,4
52,209,46,MALE,93307,26462,48,24,NEWISH-Ford-Mustang,4
67,263,40,FEMALE,926,26306,39,19,OLDISH-Ford-F150,4
69,276,49,FEMALE,10467,29044,33,16,OLDISH-Ford-Escape,4

In [30]:
tmp_df = df[(df.AGE == 33) | (df.GENDER == 'FEMALE')]
tmp_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
0,3,35,FEMALE,60647,35283,22,11,NEWISH-GMC-Acadia,3
1,13,39,FEMALE,92335,35008,51,25,OLDISH-BMW-430i,3
2,15,38,FEMALE,77449,59198,56,28,NEWISH-Buick-Regal,3
4,24,42,FEMALE,90805,32565,53,26,OLDISH-Ford-Explorer,4
6,32,44,FEMALE,85364,31515,11,5,OLDISH-Nissan-Altima,4

### Row selection with alternate syntax

In [31]:
tmp_df = df[(df['AGE'] > 38) & (df['SALARY'] < 30000)]
tmp_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
11,50,41,FEMALE,10467,29044,79,39,OLDISH-Toyota-Prius,4
29,122,42,FEMALE,90044,22091,42,21,NEWISH-Nissan-Rogue,4
52,209,46,MALE,93307,26462,48,24,NEWISH-Ford-Mustang,4
67,263,40,FEMALE,926,26306,39,19,OLDISH-Ford-F150,4
69,276,49,FEMALE,10467,29044,33,16,OLDISH-Ford-Escape,4

### Pick a few rows randomly

In [32]:
df_sample = df.sample(3)
df_sample.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
4668,7860,34,MALE,79912,48627,58,29,NEWISH-Hyundai-Santa Fe,3
6680,9980,41,MALE,77036,26931,41,20,OLDISH-Toyota-Corrola,4
7570,10889,36,FEMALE,87121,34359,63,31,OLDISH-Chrysler-200,3

### One hot encode a column
Here we would like to move from a categorical representation of gender to a one hot encoding more suitable for
feeding to a machine learning algorithm.

In [50]:
df['GENDER'].head()

0    FEMALE
1    FEMALE
2    FEMALE
3      MALE
4    FEMALE
Name: GENDER, dtype: object

In [51]:
tmp_df = pd.get_dummies(df['GENDER'])
tmp_df.head()

   FEMALE  MALE
0       1     0
1       1     0
2       1     0
3       0     1
4       1     0

Here was move our target variable, SALARY, to be the first column, and concatenate the new one-hot-encoded version
of gender, plus the rest of our original dataframe, minus salary and gender.

In [54]:
new_df = pd.concat([df['SALARY'], tmp_df, df.drop(['GENDER','SALARY'], axis=1)], axis=1)
new_df.head()

,SALARY,FEMALE,MALE,USER_ID,AGE,LOCATION,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
0,35283,1,0,3,35,60647,22,11,NEWISH-GMC-Acadia,3
1,35008,1,0,13,39,92335,51,25,OLDISH-BMW-430i,3
2,59198,1,0,15,38,77449,56,28,NEWISH-Buick-Regal,3
3,86488,0,1,20,40,77494,73,36,OLDISH-Ford-Fusion,4
4,32565,1,0,24,42,90805,53,26,OLDISH-Ford-Explorer,4

### Train / test split a dataframe

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['AGE','GENDER','LOCATION']], 
                                                    df['SALARY'], 
                                                    test_size=0.25, random_state=1)

In [34]:
print('Training shape X: {}, y: {}'.format(X_train.shape, y_train.shape))
print('Testing  shape X: {}, y: {}'.format(X_test.shape, y_test.shape))

Training shape X: (17523, 3), y: (17523,)
Testing  shape X: (5841, 3), y: (5841,)

### Get the value from a particular cell

In [35]:
df.iloc[10]

USER_ID                            46
AGE                                35
GENDER                           MALE
LOCATION                        90805
SALARY                          32565
FAV_CLUSTER                        70
FAV_MODEL                          35
FAV            NEWISH-Hyundai-Elantra
DECADE                              3
Name: 10, dtype: object

In [36]:
age = df.iloc[10][1]
age

35

### Access subset of columns in specific order
This is helpful if you are looking to save part of your data to a csv file.

In [37]:
df[['SALARY', 'GENDER', 'LOCATION']]

       SALARY  GENDER  LOCATION
0       35283  FEMALE     60647
1       35008  FEMALE     92335
2       59198  FEMALE     77449
3       86488    MALE     77494
4       32565  FEMALE     90805
5       22072    MALE     10458
6       31515  FEMALE     85364
7       42970    MALE     92154
8       41355    MALE     60618
9       37360  FEMALE     11377
10      32565    MALE     90805
11      29044  FEMALE     10467
12      41621    MALE     91706
13      24216  FEMALE     78577
14      32702  FEMALE     75211
15      33656    MALE     90250
16      29044    MALE     10467
17      48627    MALE     79912
18      26462  FEMALE     93307
19      34746  FEMALE     11368
20      40279    MALE     60629
21      67190  FEMALE     22193
22      22091    MALE     90044
23      52931  FEMALE     77083
24      32327    MALE     11230
25      49923  FEMALE     92704
26      60427    MALE     30044
27      31013    MALE     11235
28      31515    MALE     85364
29      22091  FEMALE     90044
...       ...     ...       ...
23334   42970    MALE     92154
23335   39141  FEMALE     30349
23336   68682  FEMALE     66062
23337   34359    MALE     87121
23338   41621    MALE     91706
23339   68682    MALE     66062
23340   30995    MALE     93257
23341   41621    MALE     91706
23342   36001  FEMALE     95823
23343   41621    MALE     91706
23344   31532    MALE     75217
23345   39225  FEMALE     91331
23346   20839  FEMALE     11212
23347   31013  FEMALE     11235
23348   71424    MALE     30043
23349   42970  FEMALE     92154
23350   71424  FEMALE     30043
23351   60254    MALE     75052
23352   30995    MALE     93257
23353   59198    MALE     77449
23354   72384    MALE     93065
23355   55185    MALE     91710
23356   78527  FEMALE     77429
23357   59198    MALE     77449
23358   39141    MALE     30349
23359   53486  FEMALE     23464
23360   35008    MALE     92335
23361   32565    MALE     90805
23362   40279  FEMALE     60629
23363   37141    MALE     37211

[23364 rows x 3 columns]

### Sort rows

In [38]:
tmp_df = df[(df['AGE'] > 38) & (df['SALARY'] < 30000)].sort_values('AGE', ascending=False)
tmp_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
19559,23179,57,FEMALE,78577,24216,48,24,NEWISH-Ford-Mustang,5
21912,26356,56,FEMALE,78577,24216,58,29,NEWISH-Hyundai-Santa Fe,5
1899,4395,56,FEMALE,90044,22091,63,31,OLDISH-Chrysler-200,5
5456,8712,53,FEMALE,926,26306,56,28,NEWISH-Buick-Regal,5
10033,13380,52,FEMALE,10452,20606,50,25,NEWISH-BMW-430i,5

### Dataframe values as a numpy array

In [41]:
my_array = df[df.AGE > 51].values
print(type(my_array))
my_array[:5]

<class 'numpy.ndarray'>

array([[3182, 54, 'MALE', 93257, 30995, 40, 20, 'NEWISH-Toyota-Corrola',
        5],
       [3532, 54, 'FEMALE', 90250, 33656, 49, 24, 'OLDISH-Ford-Mustang',
        5],
       [4395, 56, 'FEMALE', 90044, 22091, 63, 31, 'OLDISH-Chrysler-200',
        5],
       [4691, 53, 'MALE', 28269, 61899, 66, 33,
        'NEWISH-Chevrolet-Camaro', 5],
       [5538, 53, 'MALE', 90255, 30375, 58, 29,
        'NEWISH-Hyundai-Santa Fe', 5]], dtype=object)

### Change column data type

In [42]:
tmp_df['LOCATION'] = tmp_df.LOCATION.astype(str)
tmp_df.dtypes

USER_ID         int64
AGE             int64
GENDER         object
LOCATION       object
SALARY          int64
FAV_CLUSTER     int64
FAV_MODEL       int64
FAV            object
DECADE          int64
dtype: object

### List unique values

In [43]:
df['GENDER'].unique()

array(['FEMALE', 'MALE'], dtype=object)

### Select set of rows matching a set of values (isin)

In [44]:
ages = [38, 42]
a_df = df[df['AGE'].isin(ages)]
a_df.head()

,USER_ID,AGE,GENDER,LOCATION,SALARY,FAV_CLUSTER,FAV_MODEL,FAV,DECADE
2,15,38,FEMALE,77449,59198,56,28,NEWISH-Buick-Regal,3
4,24,42,FEMALE,90805,32565,53,26,OLDISH-Ford-Explorer,4
13,67,38,FEMALE,78577,24216,44,22,NEWISH-Chevrolet-Suburban,3
20,86,42,MALE,60629,40279,51,25,OLDISH-BMW-430i,4
26,109,38,MALE,30044,60427,72,36,NEWISH-Ford-Fusion,3

### Group by columns

In [45]:
tmp_df = df.groupby(['GENDER', 'AGE'])
for key, item in tmp_df:
    print(tmp_df.get_group(key), "\n\n")

       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
14809    18193   25  FEMALE     93550   37484           55         27
22012    26533   25  FEMALE     93033   46342           29         14
23100    29008   25  FEMALE     30043   71424           65         32

                          FAV  DECADE
14809  OLDISH-Chevrolet-Tahoe       2
22012  OLDISH-Volkswagen-Golf       2
23100        OLDISH-Dodge-Ram       2


       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
6872     10172   26  FEMALE     91911   38010           55         27
9925     13270   26  FEMALE     78521   23426           69         34
12361    15724   26  FEMALE     10002   24022           49         24
16074    19484   26  FEMALE     91331   39225           31         15

                          FAV  DECADE
6872   OLDISH-Chevrolet-Tahoe       2
9925      OLDISH-Cadillac-XT5       2
12361     OLDISH-Ford-Mustang       2
16074        OLDISH-Ford-Edge       2


      USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
870      2546   27  FEMALE     10458   22072           22         11
1626     3936   27  FEMALE     92704   49923           56         28
2652     5478   27  FEMALE     85364   31515           65         32
5649     8912   27  FEMALE     91331   39225           42         21
7194    10503   27  FEMALE     22193   67190           50         25
7951    11275   27  FEMALE     93257   30995           51         25

                      FAV  DECADE
870     NEWISH-GMC-Acadia       2
1626   NEWISH-Buick-Regal       2
2652     OLDISH-Dodge-Ram       2
5649  NEWISH-Nissan-Rogue       2
7194      NEWISH-BMW-430i       2
7951      OLDISH-BMW-430i       2


       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
1209      3216   28  FEMALE     92335   35008           66         33
1654      3983   28  FEMALE     93065   72384           36         18
4127      7257   28  FEMALE     91710   55185           39         19
4178      7311   28  FEMALE     60647   35283           29         14
9539     12883   28  FEMALE     79912   48627           66         33
10751    14102   28  FEMALE     10029   22232           35         17
12540    15903   28  FEMALE     10452   20606           27         13
13698    17071   28  FEMALE     11206   18661           45         22
15019    18409   28  FEMALE     87121   34359           32         16
15572    18967   28  FEMALE     93257   30995           61         30
19213    22796   28  FEMALE     60625   40083           55         27
20745    24649   28  FEMALE     92336   55340           73         36
20872    24832   28  FEMALE     10452   20606           51         25
21552    25806   28  FEMALE     11226   29498           24         12
22903    28405   28  FEMALE     91342   48744           81         40
23207    29389   28  FEMALE     11377   37360           33         16

                              FAV  DECADE
1209      NEWISH-Chevrolet-Camaro       2
1654           NEWISH-Honda-Pilot       2
4127             OLDISH-Ford-F150       2
4178       OLDISH-Volkswagen-Golf       2
9539      NEWISH-Chevrolet-Camaro       2
10751  OLDISH-Chevrolet-Silverado       2
12540            OLDISH-Volvo-240       2
13698   OLDISH-Chevrolet-Suburban       2
15019          NEWISH-Ford-Escape       2
15572       OLDISH-Subaru-Outback       2
19213      OLDISH-Chevrolet-Tahoe       2
20745          OLDISH-Ford-Fusion       2
20872             OLDISH-BMW-430i       2
21552            NEWISH-GMC-Yukon       2
22903            OLDISH-Volvo-V60       2
23207          OLDISH-Ford-Escape       2


       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
191        802   29  FEMALE     79912   48627           47         23
465       1573   29  FEMALE     77036   26931           57         28
669       2086   29  FEMALE     92553   38554           38         19
994       2801   29  FEMALE     92683   49686           63         31
1061      2928   29  FEMALE     77573   68458           46         23
1269      3319   29  FEMALE     28269   61899           70         35
1952      4489   29  FEMALE     92335   35008           57         28
2062      4664   29  FEMALE     77084   53075           50         25
2219      4880   29  FEMALE     90650   46012           67         33
3484      6508   29  FEMALE     85364   31515           43         21
3779      6857   29  FEMALE     90044   22091           69         34
3846      6935   29  FEMALE     10458   22072           73         36
4077      7201   29  FEMALE     10453   21109           22         11
4806      8013   29  FEMALE     79912   48627           42         21
4995      8218   29  FEMALE     93550   37484           37         18
5911      9184   29  FEMALE     92376   37568           62         31
6540      9837   29  FEMALE     90706   39362           51         25
7258     10570   29  FEMALE     91342   48744           52         26
8043     11370   29  FEMALE     75070   84847           52         26
8917     12253   29  FEMALE     75211   32702           61         30
9266     12606   29  FEMALE     30043   71424           62         31
9353     12694   29  FEMALE     10452   20606           51         25
12071    15434   29  FEMALE     92345   41423           68         34
12902    16268   29  FEMALE     90250   33656           44         22
13255    16625   29  FEMALE     77083   52931           76         38
13980    17355   29  FEMALE     92154   42970           67         33
14417    17797   29  FEMALE     93033   46342           39         19
14544    17925   29  FEMALE     11377   37360           43         21
14806    18190   29  FEMALE     11235   31013           58         29
15225    18618   29  FEMALE     90805   32565           39         19
15245    18638   29  FEMALE     95823   36001           47         23
16901    20329   29  FEMALE     91706   41621           41         20
18283    21782   29  FEMALE     77084   53075           33         16
20312    24086   29  FEMALE     79912   48627           27         13
20958    24949   29  FEMALE     90706   39362           58         29
22944    28541   29  FEMALE     77084   53075           36         18

                             FAV  DECADE
191     OLDISH-Chrysler-Pacifica       2
465           OLDISH-Buick-Regal       2
669             NEWISH-Ford-F150       2
994          OLDISH-Chrysler-200       2
1061    NEWISH-Chrysler-Pacifica       2
1269      NEWISH-Hyundai-Elantra       2
1952          OLDISH-Buick-Regal       2
2062             NEWISH-BMW-430i       2
2219     OLDISH-Chevrolet-Camaro       2
3484         OLDISH-Nissan-Rogue       2
3779         OLDISH-Cadillac-XT5       2
3846          OLDISH-Ford-Fusion       2
4077           NEWISH-GMC-Acadia       2
4806         NEWISH-Nissan-Rogue       2
4995          OLDISH-Honda-Pilot       2
5911         NEWISH-Chrysler-200       2
6540             OLDISH-BMW-430i       2
7258        NEWISH-Ford-Explorer       2
8043        NEWISH-Ford-Explorer       2
8917       OLDISH-Subaru-Outback       2
9266         NEWISH-Chrysler-200       2
9353             OLDISH-BMW-430i       2
12071        NEWISH-Cadillac-XT5       2
12902  NEWISH-Chevrolet-Suburban       2
13255   NEWISH-Cadillac-Escalade       2
13980    OLDISH-Chevrolet-Camaro       2
14417           OLDISH-Ford-F150       2
14544        OLDISH-Nissan-Rogue       2
14806    NEWISH-Hyundai-Santa Fe       2
15225           OLDISH-Ford-F150       2
15245   OLDISH-Chrysler-Pacifica       2
16901      OLDISH-Toyota-Corrola       2
18283         OLDISH-Ford-Escape       2
20312           OLDISH-Volvo-240       2
20958    NEWISH-Hyundai-Santa Fe       2
22944         NEWISH-Honda-Pilot       2


       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
312       1171   30  FEMALE     10452   20606           45         22
409       1403   30  FEMALE     78572   23799           70         35
1425      3575   30  FEMALE     10025   49733           30         15
1576      3864   30  FEMALE     90706   39362           39         19
1625      3935   30  FEMALE     11230   32327           47         23
2116      4737   30  FEMALE     94544   49452           70         35
2825      5696   30  FEMALE     95076   45354           66         33
3168      6120   30  FEMALE     11368   34746           71         35
3514      6549   30  FEMALE     77479   96118           42         21
4313      7464   30  FEMALE     11214   33765           47         23
4569      7750   30  FEMALE     91744   46792           47         23
5769      9037   30  FEMALE     91710   55185           74         37
5875      9148   30  FEMALE     91911   38010           37         18
5912      9185   30  FEMALE     60625   40083           20         10
5996      9276   30  FEMALE     95076   45354           70         35
6235      9523   30  FEMALE     77479   96118           51         25
6391      9683   30  FEMALE     93257   30995           48         24
6515      9811   30  FEMALE     90201   30029           50         25
7013     10318   30  FEMALE     28269   61899           41         20
7214     10523   30  FEMALE     11214   33765           42         21
7255     10566   30  FEMALE     78521   23426           52         26
7317     10631   30  FEMALE     93550   37484           64         32
7358     10674   30  FEMALE     23464   53486           27         13
7379     10696   30  FEMALE     11207   24163           49         24
7849     11171   30  FEMALE     95076   45354           47         23
8202     11531   30  FEMALE     10467   29044           56         28
8278     11608   30  FEMALE     91342   48744           57         28
8542     11876   30  FEMALE     75211   32702           42         21
8901     12237   30  FEMALE     91911   38010           54         27
8918     12254   30  FEMALE     91910   42970           59         29
...        ...  ...     ...       ...     ...          ...        ...
12013    15376   30  FEMALE     91709   78336           50         25
12702    16066   30  FEMALE     79912   48627           59         29
13114    16483   30  FEMALE     11230   32327           16          8
14599    17980   30  FEMALE     79936   42857           53         26
14843    18229   30  FEMALE     95823   36001           45         22
14932    18319   30  FEMALE     10029   22232           66         33
15223    18616   30  FEMALE     10468   26852           46         23
15299    18693   30  FEMALE     78577   24216           66         33
15858    19261   30  FEMALE      8701   35647           35         17
16199    19611   30  FEMALE     92154   42970           24         12
16233    19645   30  FEMALE     91911   38010           44         22
17490    20940   30  FEMALE     10453   21109           53         26
17616    21071   30  FEMALE     91744   46792           30         15
18071    21555   30  FEMALE     77584   70113           57         28
18191    21678   30  FEMALE     95823   36001           75         37
18499    22018   30  FEMALE     10462   33735           37         18
18555    22083   30  FEMALE     90805   32565           42         21
18795    22339   30  FEMALE     77083   52931           65         32
19067    22639   30  FEMALE     92376   37568           57         28
19198    22778   30  FEMALE     60647   35283           43         21
19639    23272   30  FEMALE     79936   42857           28         14
19825    23493   30  FEMALE     91709   78336           42         21
20498    24314   30  FEMALE     11234   51446           45         22
20839    24786   30  FEMALE     93307   26462           46         23
20925    24901   30  FEMALE     77036   26931           45         22
21038    25066   30  FEMALE     91342   48744           39         19
21453    25666   30  FEMALE     93307   26462           23         11
21694    26015   30  FEMALE     77036   26931           69         34
22102    26685   30  FEMALE     10462   33735           64         32
22936    28511   30  FEMALE     11219   26648           31         15

                              FAV  DECADE
312     OLDISH-Chevrolet-Suburban       3
409        NEWISH-Hyundai-Elantra       3
1425             NEWISH-Ford-Edge       3
1576             OLDISH-Ford-F150       3
1625     OLDISH-Chrysler-Pacifica       3
2116       NEWISH-Hyundai-Elantra       3
2825      NEWISH-Chevrolet-Camaro       3
3168       OLDISH-Hyundai-Elantra       3
3514          NEWISH-Nissan-Rogue       3
4313     OLDISH-Chrysler-Pacifica       3
4569     OLDISH-Chrysler-Pacifica       3
5769         NEWISH-Dodge-Caravan       3
5875           OLDISH-Honda-Pilot       3
5912          NEWISH-Chrysler-300       3
5996       NEWISH-Hyundai-Elantra       3
6235              OLDISH-BMW-430i       3
6391          NEWISH-Ford-Mustang       3
6515              NEWISH-BMW-430i       3
7013        OLDISH-Toyota-Corrola       3
7214          NEWISH-Nissan-Rogue       3
7255         NEWISH-Ford-Explorer       3
7317             NEWISH-Dodge-Ram       3
7358             OLDISH-Volvo-240       3
7379          OLDISH-Ford-Mustang       3
7849     OLDISH-Chrysler-Pacifica       3
8202           NEWISH-Buick-Regal       3
8278           OLDISH-Buick-Regal       3
8542          NEWISH-Nissan-Rogue       3
8901       NEWISH-Chevrolet-Tahoe       3
8918      OLDISH-Hyundai-Santa Fe       3
...                           ...     ...
12013             NEWISH-BMW-430i       3
12702     OLDISH-Hyundai-Santa Fe       3
13114      NEWISH-Ford-Expedition       3
14599        OLDISH-Ford-Explorer       3
14843   OLDISH-Chevrolet-Suburban       3
14932     NEWISH-Chevrolet-Camaro       3
15223    NEWISH-Chrysler-Pacifica       3
15299     NEWISH-Chevrolet-Camaro       3
15858  OLDISH-Chevrolet-Silverado       3
16199            NEWISH-GMC-Yukon       3
16233   NEWISH-Chevrolet-Suburban       3
17490        OLDISH-Ford-Explorer       3
17616            NEWISH-Ford-Edge       3
18071          OLDISH-Buick-Regal       3
18191        OLDISH-Dodge-Caravan       3
18499          OLDISH-Honda-Pilot       3
18555         NEWISH-Nissan-Rogue       3
18795            OLDISH-Dodge-Ram       3
19067          OLDISH-Buick-Regal       3
19198         OLDISH-Nissan-Rogue       3
19639      NEWISH-Volkswagen-Golf       3
19825         NEWISH-Nissan-Rogue       3
20498   OLDISH-Chevrolet-Suburban       3
20839    NEWISH-Chrysler-Pacifica       3
20925   OLDISH-Chevrolet-Suburban       3
21038            OLDISH-Ford-F150       3
21453           OLDISH-GMC-Acadia       3
21694         OLDISH-Cadillac-XT5       3
22102            NEWISH-Dodge-Ram       3
22936            OLDISH-Ford-Edge       3

[69 rows x 9 columns]


       USER_ID  AGE  GENDER  LOCATION  SALARY  FAV_CLUSTER  FAV_MODEL  \
66         255   31  FEMALE     92704   49923           33         16
234        935   31  FEMALE     10468   26852           46         23
756       2312   31  FEMALE     90255   30375           40         20
1644      3962   31  FEMALE     75217   31532           41         20
1932      4451   31  FEMALE     87121   34359           76         38
2950      5851   31  FEMALE     91335   40792           47         23
3036      5962   31  FEMALE     91910   42970           44         22
3079      6018   31  FEMALE     91911   38010           63         31
4190      7325   31  FEMALE     92345   41423           60         30
4545      7723   31  FEMALE     90650   46012           48         24
4767      7969   31  FEMALE     93257   30995           35         17
4938      8156   31  FEMALE     91342   48744           42         21
4985      8208   31  FEMALE     91331   39225           45         22
5022      8246   31  FEMALE     60618   41355           64         32
5109      8343   31  FEMALE     91335   40792           38         19
5228      8468   31  FEMALE     90650   46012           41         20
5382      8633   31  FEMALE     11212   20839           41         20
5549      8807   31  FEMALE     91744   46792           74         37
5583      8842   31  FEMALE     10453   21109           61         30
5823      9094   31  FEMALE     91706   41621           45         22
5944      9219   31  FEMALE     92804   41887           65         32
6010      9292   31  FEMALE     77084   53075           42         21
6185      9470   31  FEMALE     60629   40279           36         18
6365      9656   31  FEMALE     77449   59198           62         31
7063     10368   31  FEMALE     91342   48744           51         25
7424     10741   31  FEMALE     92376   37568           59         29
7625     10944   31  FEMALE     77584   70113           34         17
7788     11107   31  FEMALE     90706   39362           45         22
8190     11519   31  FEMALE     66062   68682           42         21
8195     11524   31  FEMALE     91335   40792           47         23
...        ...  ...     ...       ...     ...          ...        ...
16457    19875   31  FEMALE     11219   26648           35         17
16495    19915   31  FEMALE     90201   30029           56         28
16781    20206   31  FEMALE     23464   53486           59         29
17309    20747   31  FEMALE     90011   23851           40         20
17464    20912   31  FEMALE     37013   46063           41         20
17936    21413   31  FEMALE     77084   53075            7          3
18087    21571   31  FEMALE     10025   49733           77         38
19025    22593   31  FEMALE     93550   37484           56         28
19137    22715   31  FEMALE     60617   35534           42         21
19292    22878   31  FEMALE     90805   32565           34         17
19434    23042   31  FEMALE     90201   30029           48         24
19787    23446   31  FEMALE     94565   48523           29         14
19857    23528   31  FEMALE     37211   37141           56         28
20086    23801   31  FEMALE     93257   30995           48         24
20089    23805   31  FEMALE     78572   23799           30         15
20138    23871   31  FEMALE     90280   35744           49         24
20214    23961   31  FEMALE     28269   61899           54         27
20266    24024   31  FEMALE     90255   30375           53         26
20710    24592   31  FEMALE     91335   40792           40         20
20952    24943   31  FEMALE     77494   86488           39         19
20977    24976   31  FEMALE     11206   18661           34         17
21132    25189   31  FEMALE     94565   48523           17          8
21279    25406   31  FEMALE     92553   38554           79         39
21301    25441   31  FEMALE     90250   33656           50         25
21608    25892   31  FEMALE     10468   26852           49         24
21905    26345   31  FEMALE     22193   67190           55         27
22385    27238   31  FEMALE     79936   42857           23         11
22779    28088   31  FEMALE     77494   86488           58         29
22990    28675   31  FEMALE     60617   35534           30         15
23173    29274   31  FEMALE     77479   96118           54         27

                              FAV  DECADE
66             OLDISH-Ford-Escape       3
234      NEWISH-Chrysler-Pacifica       3
756         NEWISH-Toyota-Corrola       3
1644        OLDISH-Toyota-Corrola       3
1932     NEWISH-Cadillac-Escalade       3
2950     OLDISH-Chrysler-Pacifica       3
3036    NEWISH-Chevrolet-Suburban       3
3079          OLDISH-Chrysler-200       3
4190        NEWISH-Subaru-Outback       3
4545          NEWISH-Ford-Mustang       3
4767   OLDISH-Chevrolet-Silverado       3
4938          NEWISH-Nissan-Rogue       3
4985    OLDISH-Chevrolet-Suburban       3
5022             NEWISH-Dodge-Ram       3
5109             NEWISH-Ford-F150       3
5228        OLDISH-Toyota-Corrola       3
5382        OLDISH-Toyota-Corrola       3
5549         NEWISH-Dodge-Caravan       3
5583        OLDISH-Subaru-Outback       3
5823    OLDISH-Chevrolet-Suburban       3
5944             OLDISH-Dodge-Ram       3